# Generated by Django 4.2.16 on 2024-11-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vlogpost', '0003_category_vlogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlogpost',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vlog_posts', to='vlogpost.category'),
        ),
    ]
